name = "FRED"
uuid = "c96c195d-a69a-47bc-8acf-270fa3d7178f"
authors = ["Vadim Elenev <47358678+elenev@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
